version: '3.8'

services:
  app:
    build: .
    container_name: simulador-credito-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: simulador_credito
      DB_USER: postgres
      DB_PASS: postgres

  postgres:
    image: postgres:14-alpine
    container_name: simulador-credito-db
    environment:
      POSTGRES_DB: simulador_credito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
